### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by alanjds** [ntoll/python-native-editor#1]
Hi.

Is there a way to put it to work on my Chrome browser?

I know that this is just an afternoon hack, but how does I put it to work? if it works at all.. ;)

**Comment by ntoll** [comment]
Hey @alanjds, this is available in the Chrome "store" here: https://chrome.google.com/webstore/search/MicroPython (it's the top one). Click on the "Add to Chrome" button and follow the instructions.

That's it!

I hope to update the application at the end of next week with the latest version of the MicroPython runtime (that's also being released at the same time).

Once you've got it to work, please let me know and close this issue.

Happy to answer questions and best of luck! MicroPython tutorials and documentation is here:

https://microbit-micropython.readthedocs.io/en/latest/

:smile:

**Comment by alanjds** [comment]
It worked. Thanks.
